resources:
# Firewall rule
- name: services-firewall
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceTags:
    - api-gateway-firewll
    targetTags:
    - services-firewall
    allowed:
    - IPProtocol: TCP
      ports:
      - 8080

# Firewall rule
- name: api-gateway-firewall
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 0.0.0.0/0
    targetTags:
    - api-gateway-firewall
    allowed:
    - IPProtocol: TCP
      ports:
      - 8000

# Firewall rule
- name: db-firewall-auth
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 10.128.0.52/32
    targetTags:
    - db-firewall-auth
    allowed:
    - IPProtocol: TCP
      ports:
      - 5432

# Firewall rule
- name: db-firewall-signatory
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 10.128.0.55/32
    targetTags:
    - db-firewall-signatory
    allowed:
    - IPProtocol: TCP
      ports:
      - 5432

# Firewall rule
- name: db-firewall-cards
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 10.128.0.56/32
    targetTags:
    - db-firewall-cards
    allowed:
    - IPProtocol: TCP
      ports: 
      - 27017

# Instance
- name: api-gateway
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.51
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - api-gateway-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install git -y
          sudo dpkg --configure -a
          sudo apt-get install -y docker.io git
          sudo systemctl start docker
          sudo systemctl enable docker

          if [ ! -d "/apps" ]; then
            sudo mkdir /apps
            cd /apps
            sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
            cd MS-BancoAlpes
          else
            cd /apps/MS-BancoAlpes
            sudo git pull
          fi

          cd Deployment

          sudo usermod -aG docker $USER
          newgrp docker <<EONG
          docker ps -aq -f name=kong | xargs -r docker rm -f
          docker network ls -q -f name=kong-net | xargs -r docker network rm
          docker network create kong-net
          sudo docker run -d --name kong --network=kong-net -v "$(pwd):/kong/declarative/" -e "KONG_DATABASE=off" -e "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yaml" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" -e "KONG_ADMIN_GUI_URL=http://localhost:8002" -p 8000:8000 -p 8001:8001 -p 8002:8002 kong/kong-gateway:2.7.2.0-alpine
          sudo docker restart kong
          EONG

# Instance
- name: auth-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.52
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install git -y
          sudo apt install python3-pip -y

          if [ ! -d "/apps" ]; then
            sudo mkdir /apps
            cd /apps
            sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
            cd MS-BancoAlpes
          else
            cd /apps/MS-BancoAlpes
            sudo git pull
          fi

          sudo pip3 install -r Deployment/requirements.txt
          cd Auth
          sudo python3 manage.py makemigrations
          sudo python3 manage.py migrate
          sudo nohup python3 manage.py runserver 0.0.0.0:8080 &

# Instance
- name: home-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.53
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install git -y
          sudo apt install python3-pip -y

          if [ ! -d "/apps" ]; then
            sudo mkdir /apps
            cd /apps
            sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
            cd MS-BancoAlpes
          else
            cd /apps/MS-BancoAlpes
            sudo git pull
          fi

          sudo pip3 install -r Deployment/requirements.txt
          cd Home
          sudo python3 manage.py makemigrations
          sudo python3 manage.py migrate
          sudo nohup python3 manage.py runserver 0.0.0.0:8080 &

# Instance
- name: crm-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.54
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install git -y
          sudo apt install python3-pip -y

          if [ ! -d "/apps" ]; then
            sudo mkdir /apps
            cd /apps
            sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
            cd MS-BancoAlpes
          else
            cd /apps/MS-BancoAlpes
            sudo git pull
          fi

          sudo pip3 install -r Deployment/requirements.txt
          cd Users
          sudo python3 manage.py makemigrations
          sudo python3 manage.py migrate
          sudo nohup python3 manage.py runserver 0.0.0.0:8080 &

# Instance
- name: signatory-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.55
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install git -y
          sudo apt install python3-pip -y

          if [ ! -d "/apps" ]; then
            sudo mkdir /apps
            cd /apps
            sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
            cd MS-BancoAlpes
          else
            cd /apps/MS-BancoAlpes
            sudo git pull
          fi

          sudo pip3 install -r Deployment/requirements.txt
          cd Manejador
          sudo nohup python3 app.py &

# Instance
- name: cards-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.56
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install git -y
          sudo apt install python3-pip -y

          if [ ! -d "/apps" ]; then
            sudo mkdir /apps
            cd /apps
            sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
            cd MS-BancoAlpes
          else
            cd /apps/MS-BancoAlpes
            sudo git pull
          fi

          sudo pip3 install -r Deployment/requirements.txt
          cd tarjetasMongo
          sudo nohup python3 manage.py runserver 0.0.0.0:8080 &
          

# Instance
- name: auth-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.57
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - db-firewall-auth
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo apt-get install -y postgresql-11 postgresql-contrib-11

          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/11/main/postgresql.conf
          echo "max_connections = 2000" | sudo tee -a /etc/postgresql/11/main/postgresql.conf

          echo -e "# TYPE  DATABASE        USER            ADDRESS                 METHOD\nlocal   all             all                                     trust\nlocal   all             banco_alpes                             md5\nhost    all             all             127.0.0.1/32            trust\nhost    all             all             ::1/128                 trust\nhost    all             all             0.0.0.0/0               md5" | sudo tee /etc/postgresql/11/main/pg_hba.conf

          sudo systemctl restart postgresql
          sudo -u postgres psql -c "CREATE USER banco_alpes WITH PASSWORD 'banco_alpes';"
          sudo -u postgres createdb -O banco_alpes banco_alpes_db


# Instance
# - name: signatory-db
#   type: compute.v1.instance
#   properties:
#     zone: us-central1-a
#     machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
#     disks:
#     - deviceName: boot
#       type: PERSISTENT
#       boot: true
#       autoDelete: true
#       initializeParams:
#         sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
#     networkInterfaces:
#     - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
#       networkIP: 10.128.0.58
#       accessConfigs:
#       - name: External NAT
#         type: ONE_TO_ONE_NAT
#     tags:
#       items:
#       - services-firewall
#     metadata:
#       items:
#       - key: startup-script
#         value: |
#           sudo apt-get update
#           sudo apt install python3-pip -y

#           if [ ! -d "/apps" ]; then
#             sudo mkdir /apps
#             cd /apps
#             sudo git clone https://github.com/Sprint-4-Microservicios/MS-BancoAlpes.git
#             cd BancoAlpes
#           else
#             cd /apps/BancoAlpes
#             sudo git pull
#           fi

# Instance
- name: cards-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes-424811/global/networks/default
      networkIP: 10.128.0.59
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - db-firewall-cards
    metadata:
      items:
      - key: startup-script
        value: |
          sudo apt-get update
          sudo dpkg --configure -a
          sudo apt-get install -y docker.io git
          sudo systemctl start docker
          sudo systemctl enable docker

          sudo docker run -e MONGO_INITDB_ROOT_USERNAME=banco_alpes -e MONGO_INITDB_ROOT_PASSWORD=banco_alpes -p 27017:27017 -d mongo
