resources:
# Firewall rule
- name: services-firewall
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceTags:
    - api-gateway-firewll
    targetTags:
    - services-firewall
    allowed:
    - IPProtocol: TCP
      ports:
      - 8080

# Firewall rule
- name: api-gateway-firewall
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 0.0.0.0/0
    targetTags:
    - api-gateway-firewall
    allowed:
    - IPProtocol: TCP
      ports:
      - 8000

# Firewall rule
- name: db-firewall-auth
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 10.128.0.52/32
    targetTags:
    - db-firewall-auth
    allowed:
    - IPProtocol: TCP
      ports:
      - 27017

# Firewall rule
- name: db-firewall-signatory
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 10.128.0.55/32
    targetTags:
    - db-firewall-signatory
    allowed:
    - IPProtocol: TCP
      ports:
      - 5432

# Firewall rule
- name: db-firewall-cards
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 10.128.0.56/32
    targetTags:
    - db-firewall-cards
    allowed:
    - IPProtocol: TCP
      ports:
      - 8080

# Instance
- name: api-gateway
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.51
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - api-gateway-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo dpkg --configure -a
          sudo apt-get install -y docker.io git
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo apt install python3-pip -y

# Instance
- name: auth-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.52
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# Instance
- name: home-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.53
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# Instance
- name: crm-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.54
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# Instance
- name: signatory-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.55
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# Instance
- name: cards-service
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.56
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# DataBase
- name: auth-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.57
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# DataBase
- name: signatory-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.58
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update

# DataBase
- name: cards-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.59
    tags:
      items:
      - services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          apt-get update